# Generated by Django 5.0.6 on 2024-05-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_videos_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
