# Generated by Django 5.0.6 on 2024-05-09 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_videos_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='uploaded_by',
            new_name='user',
        ),
    ]
