# Generated by Django 5.0.6 on 2024-05-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='banner',
            new_name='poster',
        ),
        migrations.AddField(
            model_name='videos',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videos',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videos',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
