# Generated by Django 5.0.6 on 2024-05-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
